# Generated by Django 3.2 on 2021-04-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("name", models.CharField(max_length=50, verbose_name="Ship name")),
                (
                    "imo",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="IMO number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(verbose_name="Position timestamp")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "ship_imo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="ships.ship",
                        verbose_name="Ship IMO",
                    ),
                ),
            ],
        ),
    ]
